version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-2.7
jobs:
  test-2.7: &test-template
    docker:
      - image: circleci/python:2.7-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt install --quiet libgtk-3-dev
            sudo pip install --upgrade pytest pytest-mock pytest-cov --progress-bar off
            sudo pip install -e .
      - run:
          name: Run tests
          command: make test
